[package]
name = "wasm-test"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = ["Request", "RequestInit", "RequestMode", "Response", "Window"] }

[lib]
crate-type = ["cdylib"]
